sudo: required
services:
  - docker
language: bash
env:
  global:
    - secure: R+bA4edr7Py5f/lwvJFjdcWtz+V/2F7Tg7LWKraOiNgoQhOKDByey7s6B0qOE1MVH67xCup7NMHRuBTvHh/ryvyGJ9rmJUmSli9DO4wbpXadxX2PGssbfHy7rZP/q51VOXjfvPALBRtgWdP3oD1vQCwTapNUMXyF39mTysQeFz4ck/fc9pv17Uihvjr6YGI42Yzrwi5WhJxESWwsU5js+EqAaTLnabdPvmiPsz8WWqisLo3ZxAmIIdFno5cwQVhF9Le2lOQu+5gafdbmhj25EagTyof9kuZCIfi4Ixv81a4rKN8UzySjU2Rd4uY1+mCK9AOlfBs2OxMFg9tj7RAMxXsjYol+j7uiE9/exRIIcyxemNbhI80fhdeu7bgBzN4a//0+jird9jaARcT0mpw39XHhSD3MqysGzKZoLMikN35KVo7ll/V3ygY2x7s4y6GLS+xAEF8YJLBEOf1+obFrbpzzN8CUg3R015vea7bxNYA/LdTvzcC/lbKuWCfqXU2slQbVh0AnDb8TuddUaGrcxKYjL5s+pYszSo+jmBIQ1iOdmgmrOp5nh3hwQJeS74vBgDSJa9+31JBBN/jQKMiPAk8kfJRQHrX/CI4aj9f1TxltS8DNhujPboZUu6PvN5dOjE4MZO2NTV9BrtYrdXN3xRV2x9pYrVQ3+iJ/frbAWnY=
    - secure: MoQkMjKRTPa5L05vjX8zb0DxRyvhpMBOAABeUtxVtj4Q8qIikjXIgOEzeTonpA0gQogWTH6AEAO0qOLCA2K/Li76FXufh1MqP4AZMqHjEhPnWshnKuZUx/WXp8Ey1mhWIV6if9h1RMfOzUHdang6U34QrWVUQVjUfXQEZpP3EQMZvbDgSADkXkuy4Xy53a4uW0bLvSt8fwLuejEpD5QaTV2EaKBYHS7+x+o3ggfSkDjJnVike9BJLDw3EyaI2J8uQArtkxQYo/neEbJizjB5MSS4dRPA7iLhUhf/khonM6hyKWGpzpzgA36J4SYwVj88zw5xS4z5OPoqPPMLRvVG8SIsP3UTWG6UgwF1XFPIOfci8PmiMEVT+2njdNRa05mxuLoNZlAX7XhGuIHOWFBj2CwPuZYZicImm+LgeHFR8WjmNZbADHkmqBf1zzJJYL6g+GJSKqmrcb86uYbfGl3oH1/dM64DAAjIkEf02m1N+SMnIpemhW+8cTdBfv6TEUBvFDFcaw2YlIXggXp5Z6bKZW6Ht+YyrMNyvvv+vJsdcra+sTjbch3E/4ne/VM4hjSbPbMZcBwr6CIRlsWcYlujZYDSNtHlk35JHBdudOA0jOcGdNfqd4qGmT8BM/IIpBRxiAfMJA8OMXPRRWIxe3vDTTsreZ/3Z35H8XAKFEHcVZ8=
install:
  - wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
  - chmod +x manifest-tool
script:
# Download QEMU executables
  - ./prepare-qemu.sh
# Build amd64
  - docker build -t "ngdio/mosquitto:amd64" -f amd64/Dockerfile .
# Setup QEMU
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# Build i386
  - docker build -t "ngdio/mosquitto:i386" -f i386/Dockerfile .
# Build armhf
  - docker build -t "ngdio/mosquitto:armhf" -f armhf/Dockerfile .
# Build aarch64
  - docker build -t "ngdio/mosquitto:aarch64" -f aarch64/Dockerfile .
after_success:
# Tag and push built images
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      VERSION=$(cat .VERSION)
      docker tag ngdio/mosquitto:amd64 ngdio/mosquitto:amd64-$VERSION
      docker push ngdio/mosquitto:amd64
      docker push ngdio/mosquitto:amd64-$VERSION
      docker tag ngdio/mosquitto:i386 ngdio/mosquitto:i386-$VERSION
      docker push ngdio/mosquitto:i386
      docker push ngdio/mosquitto:i386-$VERSION
      docker tag ngdio/mosquitto:armhf ngdio/mosquitto:armhf-$VERSION
      docker push ngdio/mosquitto:armhf
      docker push ngdio/mosquitto:armhf-$VERSION
      docker tag ngdio/mosquitto:aarch64 ngdio/mosquitto:aarch64-$VERSION
      docker push ngdio/mosquitto:aarch64
      docker push ngdio/mosquitto:aarch64-$VERSION
    fi
# Update manifest
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./manifest-tool --username $DOCKER_USER --password $DOCKER_PASS push from-spec manifest.yml
    fi
